// sim/index.ts — public API barrel. The ONLY import surface for /client
// and for the future Colyseus server.

export type {
  Ball,
  Body,
  Build,
  GoalTapState,
  Input,
  MatchState,
  NPC,
  Player,
  Role,
  SimState,
  Team,
  Vec2,
  WinState,
} from './types.js';

export {
  ASHBOURNE_TOWN,
  HEDGE_SPEED_MULT,
  MILL_CLIFTON,
  MILL_STURSTON,
  RIVER_SPEED_MULT,
  TOWN_SCALE,
  goalFor,
  goalMarkerFor,
  isBuilding,
  isInHedge,
  isInHedgeSlow,
  isInObstacle,
  isInRiver,
  isInWater,
  isOnBridge,
  isOutOfBounds,
  isWalkable,
  nearestLegalPoint,
  opponentGoalFor,
  pointInRect,
  scoringGoalMarker,
  speedMultiplierAt,
  type Bridge,
  type Building,
  type BuildingKind,
  type Circle,
  type GoalMarker,
  type MillName,
  type Obstacle,
  type RectZone,
  type TownMap,
  type Vec2Like,
} from './maps.js';

export {
  createWorld,
  countHugNeighbors,
  hugPackExtent,
  hugShoveAt,
  hugShoveAuthority,
  isInHugZone,
  integrateControlVelocity,
  stepWorld,
  HUG_MIN_SHOVE,
  HUG_NEIGHBOR_RADIUS,
  HUG_PACK_COUNT,
  HUG_PACK_GATHER_RADIUS,
  HUG_ZONE_RADIUS,
  type HugPackExtent,
  MOVEMENT,
  PLAYER_RADIUS,
  NPC_RADIUS,
  BALL_RADIUS,
  PLAYER_MAX_SPEED,
  NPC_MAX_SPEED,
  SIM_DT,
  SQUAD_SIZE,
  type CreateWorldOptions,
  type MovementTuning,
  type World,
} from './world.js';

export {
  DEFAULT_DIFFICULTY,
  DIFFICULTY_TUNING,
  difficultyTuning,
  type Difficulty,
  type DifficultyTuning,
} from './difficulty.js';

export {
  buildForSlot,
  hugStaminaMultForBuild,
  radiusMultForBuild,
  shoveMultForBuild,
  speedMultForBuild,
  HUGGER_HUG_STAMINA_MULT,
  HUGGER_RADIUS_MULT,
  HUGGER_SHOVE_MULT,
  HUGGER_SPEED_MULT,
  RUNNER_HUG_STAMINA_MULT,
  RUNNER_RADIUS_MULT,
  RUNNER_SHOVE_MULT,
  RUNNER_SPEED_MULT,
} from './builds.js';

export { releasePass, pickupReach, tryPickupBall, PASS_PICKUP_IMMUNITY_TICKS, PICKUP_PADDING } from './pass.js';
export {
  STAMINA_REGEN_RATE,
  STAMINA_MOVE_DRAIN,
  STAMINA_SPRINT_DRAIN,
  STAMINA_CARRY_DRAIN,
  STAMINA_RIP_DRAIN,
  STAMINA_WRIGGLE_DRAIN,
  EXHAUSTED_SPEED_MULT,
  SPRINT_SPEED_MULT,
  type StaminaEntity,
  type StaminaTick,
} from './stamina.js';

export {
  applyWriggleProgress,
  canNpcRip,
  canRip,
  canWriggle,
  clearPopPose,
  inNpcRipContest,
  inRipContest,
  npcRipContest,
  popBallFree,
  resetNpcRip,
  ripClearDistance,
  setWriggleFriction,
  tickNpcRip,
  tickWrestle,
  wrestleMode,
  NPC_RIP_COOLDOWN_TICKS,
  NPC_RIP_SUCCESS_SECONDS,
  RIP_CARRIER_MIN_NEIGHBORS,
  RIP_CLEAR_PADDING,
  RIP_GHOST_TICKS,
  RIP_GRACE_TICKS,
  RIP_IMMUNITY_TICKS,
  RIP_MIN_NEIGHBORS,
  RIP_MIN_STAMINA,
  RIP_POP_SPEED,
  RIP_REACH,
  RIP_SUCCESS_SECONDS,
  WRIGGLE_APPROACH_RADIUS,
  WRIGGLE_CONTACT_NEIGHBORS,
  WRIGGLE_INWARD_SPEED,
  WRIGGLE_NUDGE,
  WRIGGLE_PACK_AROUND_BALL,
  WRIGGLE_SHOVE_FLOOR,
  type WrestleMode,
  type WrestleTick,
} from './wrestle.js';

export {
  CARRY_SHOVE_FLOOR,
  CONTEST_STEER_RADIUS,
  GOAL_CONTEST_RADIUS,
  GOAL_DEFEND_SPEED_MULT,
  HOLD_BALL_ENGAGE_DISTANCE,
  HOLD_LOOSE_ENGAGE_DISTANCE,
  HOLD_LOOSE_HELP_COUNT,
  HOLD_RECLAIM_COUNT,
  LOOSE_BALL_SPEED_MULT,
  NPC_VS_SPRINT_BUDGET,
  SCORE_DRIVE_FORCE_MULT,
  SCORE_DRIVE_SPEED_MULT,
  SHEPHERD_RADIUS,
  TURN_UP_SWARM_RADIUS,
  clampNpcVelocities,
  isAmongClosestHolders,
  isTurnUpSwarm,
  npcIsBursting,
  npcSpeedCap,
  npcSteerTarget,
  threatenedGoalTeam,
  tickNpcStamina,
} from './npc.js';

// Match state machine + scoring (two-day event)
export {
  startMatch,
  endMatch,
  endDay,
  endEvent,
  beginDay2Placement,
  scoreGoal,
  tossUpBall,
  tickMatch,
  dayElapsedSeconds,
  dayProgress,
  dayClockMinutes,
  formatDayClock,
  nightfallAmount,
  isEarlyGoalWindow,
  DEFAULT_MATCH_DURATION_SECONDS,
  EARLY_GOAL_WINDOW_SECONDS,
  TOSS_UP_RECOVERY_SECONDS,
  DAY_CLOCK_START_HOUR,
  DAY_CLOCK_END_HOUR,
  GOAL_TAP_SPACING_TICKS,
  GOAL_TAP_MAX_CHAIN_TICKS,
} from './match.js';

export { tapGoal, tickNpcGoalTap, GOAL_REACH_DISTANCE, isCarrierAtOpponentGoal } from './goaling.js';

// Squad placement (strategy phase)
export {
  placeTeammate,
  moveControlled,
  setTeammateRole,
  isValidPlacement,
  autoPlaceOpponents,
  autoPlaceHome,
  countSideNearTurnUp,
  TOSS_UP_NEAR_RADIUS,
  TOSS_UP_PACK_PER_SIDE,
  TOSS_UP_SCATTER_MIN,
} from './placement.js';

// Switching
export {
  switchControl,
  quickSwitch,
  cycleTeammate,
  controlRing,
  teammatesByBallDistance,
  teammateAtPoint,
} from './switching.js';
